# Zadanie III – Układ równań liniowych

## Treść

Znajdź rozwiązanie $\mathbf{x} = [x_0, x_1, x_2, x_3]^T$ układu:

$$x_0 + 8x_2 + 8x_3 - 9 = 0$$
$$-x_0 - 3x_1 + x_2 + 4x_3 + 9 = 0$$
$$4x_0 - 3x_1 + 6x_2 + 9x_3 - 1 = 0$$
$$-7x_0 - 3x_1 + 4x_2 - 5x_3 + 1 = 0$$

Zapis macierzowy: $\mathbf{a}\,\mathbf{x} = \mathbf{b}$

$$\mathbf{a} = \begin{bmatrix} 1 & 0 & 8 & 8 \\ -1 & -3 & 1 & 4 \\ 4 & -3 & 6 & 9 \\ -7 & -3 & 4 & -5 \end{bmatrix}, \quad
\mathbf{b} = \begin{bmatrix} 9 \\ -9 \\ 1 \\ -1 \end{bmatrix}$$

## Narzędzie: `numpy.linalg.solve`

Funkcja `numpy.linalg.solve(a, b)` rozwiązuje układ $\mathbf{a}\mathbf{x}=\mathbf{b}$ dokładnie  
(używa eliminacji Gaussa z częściowym wyborem pivota). Działa tylko gdy det(a) ≠ 0.

In [ ]:
import numpy as np

# Macierz układu a (4×4)
a = np.array([
    [ 1,  0,  8,  8],
    [-1, -3,  1,  4],
    [ 4, -3,  6,  9],
    [-7, -3,  4, -5]
], dtype=float)

# Wektor prawych stron b
b = np.array([9, -9, 1, -1], dtype=float)

# Wyświetl dane wejściowe (jak w przykładzie z treści zadania)
print("MACIERZ a")
print(a)
print("WEKTOR b")
print(b)

In [ ]:
# Rozwiązanie układu: numpy.linalg.solve(a, b)
x = np.linalg.solve(a, b)

print("SOLUTION x")
print(x)

In [ ]:
# Weryfikacja: oblicz y = a*x - b i wyznacz jego normę
# Norma powinna być bliska 0 (błąd numeryczny rzędu 1e-14)
y = a @ x - b                        # operator @ = mnożenie macierzowe
norma = np.linalg.norm(y)            # norma euklidesowa (L2)

print(f"NORMA |ax - b| = {norma}")

## Weryfikacja ręczna

Podstawiamy $\mathbf{x}$ z powrotem do każdego równania i sprawdzamy czy prawa strona wynosi 9, -9, 1, -1.

In [ ]:
ax_wynik = a @ x
print("Sprawdzenie a @ x (powinno równać się b = [9, -9, 1, -1]):")
for i in range(4):
    print(f"  rząd {i}: a[{i}] · x = {ax_wynik[i]:.10f}  (b[{i}] = {b[i]})")

In [ ]:
# Wyznacznik macierzy – potwierdzenie, że układ ma jednoznaczne rozwiązanie
det_a = np.linalg.det(a)
print(f"det(a) = {det_a:.6f}")
print("Układ ma jednoznaczne rozwiązanie (det ≠ 0)." if abs(det_a) > 1e-10 else "UWAGA: macierz osobliwa!")

# Składowe rozwiązania
print("\nSkładowe rozwiązania:")
for i, xi in enumerate(x):
    print(f"  x{i} = {xi:.10f}")

## Oczekiwane wyniki (z treści zadania)

```
MACIERZ a
[[ 1  0  8  8]
 [-1 -3  1  4]
 [ 4 -3  6  9]
 [-7 -3  4 -5]]
WEKTOR b
[ 9 -9  1 -1]
SOLUTION x
[ 1.          2.08333333  1.91666667 -0.91666667]
NORMA |ax - b| = 3.076740298213702e-15
```

## Dlaczego norma ≠ 0?

Arytmetyka zmiennoprzecinkowa (float64) ma skończoną precyzję – około 15-16 cyfr znaczących.  
Norma rzędu $10^{-15}$ to błąd numeryczny, nie błąd algorytmu. Rozwiązanie jest poprawne.